---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Check the Calibration of Score Statistic under the Null

```{r cars}
set.seed(20191215)
source('R/utilities.R')
Rcpp::sourceCpp('src/utilities.cpp')
p = 2; n=30; B=1000
s = snew = rep(0,B)
for (i in 1:B){
  x = scale(matrix(rnorm(n*p), ncol=p)) * sqrt(n) / sqrt(n-1)
  y1 = scale(rnorm(n)) * sqrt(n) / sqrt(n-1)
  y2 = scale(rnorm(n)) * sqrt(n) / sqrt(n-1)
  coef = cubic_coeff(x, 0.95)
  s[i] = get_score(x, y1, y2)
  snew[i] = post_score(s[i], coef)
}
```

Check the calibration of the score statistic against the null distribution ($\chi_p^2$).
```{r}
sum(s > qchisq(0.95, p))/B
```

Check the same thing after the small sample correction.
```{r}
sum(snew > qchisq(0.95, p))/B
```

```{r}
par(mfrow = c(1,2))
qqplot(rchisq(B,p), s, main = 'before'); abline(0,1,col = 'red')
qqplot(rchisq(B,p), snew, main = 'after correction'); abline(0,1,col = 'red')
```

## Check the Calibration of Degree Statistic under the Null

```{r}
p = d = rep(0,1000)
for (i in 1:1000){
  bigy = mvrnormArma(100,rep(0,10),diag(10))
  bigy = scale(bigy) * sqrt(100)/sqrt(99)
  Y = bigy[, 1:9]
  y = bigy[,10]
  A = rnorm(100)
  d[i] = get_degree(as.matrix(A, ncol=1), y, Y)
  p[i] = get_p_from_degree(y, Y, d[i])
}
par(mfrow = c(1,1)); 
hist(p, 10)
```
