# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_grad_c <- function(sigw, sigv, uw, uv, x) {
    .Call('_DynamicCorrelation_get_grad_c', PACKAGE = 'DynamicCorrelation', sigw, sigv, uw, uv, x)
}

const_c <- function(sigw, sigv) {
    .Call('_DynamicCorrelation_const_c', PACKAGE = 'DynamicCorrelation', sigw, sigv)
}

#' get_score
#' The order of y1 and y2 does not matter.
#'
#' @param y1 observation of the first variable
#' @param y2 observation of the second variable
#' @param x covariate vector
#'
#' @export
#' @example
#' x = rnorm(100)
#' y1 = rnorm(100)
#' y2 = rnorm(100)
#' q = get_score(x, y1, y2)
get_score <- function(x, y1, y2) {
    .Call('_DynamicCorrelation_get_score', PACKAGE = 'DynamicCorrelation', x, y1, y2)
}

#' get_score_wv_c
#'
#' This function takes the sum of two variables, w, the difference of them, v, and one dimensional covariate x
#' and returns the score test statistic
#'
#' @param x Covariate vector
#' @param w sum of variable1 and variable2
#' @param v difference of variable1 and variable2
#' @export
get_score_wv_c <- function(x, w, v) {
    .Call('_DynamicCorrelation_get_score_wv_c', PACKAGE = 'DynamicCorrelation', x, w, v)
}

#' mvrnormArma
#'
#' This function returns n samples of multivariate normal distribution with
#' mean mu and variance Sigma.
#'
#' @param n Sample size
#' @param mu Mean vector
#' @param Sigma Variance-covariance matrix
#' @export
mvrnormArma <- function(n, mu, Sigma) {
    .Call('_DynamicCorrelation_mvrnormArma', PACKAGE = 'DynamicCorrelation', n, mu, Sigma)
}

#' get_degree_c
#'
#' This function returns a sum statistic d for vector y tested with all other variables in matrix Y against covariate x
#'
#' @param x Covariate vector
#' @param y Variable of interest
#' @param Y All other variables to test with y
#' @export
get_degree <- function(x, y, Y) {
    .Call('_DynamicCorrelation_get_degree', PACKAGE = 'DynamicCorrelation', x, y, Y)
}

#' @export
get_eta <- function(rho12, rho23, rho13) {
    .Call('_DynamicCorrelation_get_eta', PACKAGE = 'DynamicCorrelation', rho12, rho23, rho13)
}

#' @export
get_H <- function(Sigma) {
    .Call('_DynamicCorrelation_get_H', PACKAGE = 'DynamicCorrelation', Sigma)
}

#' @export
get_A1_c <- function(k, p, TT, RR, n) {
    .Call('_DynamicCorrelation_get_A1_c', PACKAGE = 'DynamicCorrelation', k, p, TT, RR, n)
}

#' @export
get_A2_c <- function(k, p, TT, RR, n) {
    .Call('_DynamicCorrelation_get_A2_c', PACKAGE = 'DynamicCorrelation', k, p, TT, RR, n)
}

#' @export
get_A3_c <- function(k, p, TT, RR, n) {
    .Call('_DynamicCorrelation_get_A3_c', PACKAGE = 'DynamicCorrelation', k, p, TT, RR, n)
}

#' @export
get_TT_RR_c <- function(A) {
    .Call('_DynamicCorrelation_get_TT_RR_c', PACKAGE = 'DynamicCorrelation', A)
}

#' @export
cubic_coeff <- function(x) {
    .Call('_DynamicCorrelation_cubic_coeff', PACKAGE = 'DynamicCorrelation', x)
}

#' @export
shuffle_x_c <- function(x, B) {
    .Call('_DynamicCorrelation_shuffle_x_c', PACKAGE = 'DynamicCorrelation', x, B)
}

#' @export
store_W_c <- function(y, smallY) {
    .Call('_DynamicCorrelation_store_W_c', PACKAGE = 'DynamicCorrelation', y, smallY)
}

#' @export
store_V_c <- function(y, smallY) {
    .Call('_DynamicCorrelation_store_V_c', PACKAGE = 'DynamicCorrelation', y, smallY)
}

#' bootstrap_c
#'
#' This function performs permutation test for given covariate x B times
#' Also takes as input W instead of Y matrix
#'
#' @param x Covariate vector
#' @param B number of permutations
#' @param W sum of the main variable and each target
#' @param V difference of the main variable and each target
#' @export
bootstrap_c <- function(x, B, W, V) {
    .Call('_DynamicCorrelation_bootstrap_c', PACKAGE = 'DynamicCorrelation', x, B, W, V)
}

